app/routes.php
<?php


View::share('title', "Exprime");
View::share('page_title', "");
View::share('website_keywords', "générateur de Memes mobile support, générateur de trolls mobile support
    images trolls pour commentaires de facebook, images Memes commentaires de facebook, images trolls marocaines,
    images trolls darija, images trolls arabe dialectal marocain, images Memes marocaines,
    images Memes darija, images Memes arabe dialectal marocain");
View::share('page_keywords', "");



if(starts_with(Request::path(),'admin'))
{
    // dd(Session::all());
    $pictures_count = Picture::all()->count();
    $users_count = User::all()->count();
    $emails_count = Email::all()->count();
    $bugs_count = 0;
    $sugs_count = 0;

    $old_pictures_count = Session::get('old_pictures_count', $pictures_count);
    $old_users_count = Session::get('old_users_count', $users_count);
    $old_emails_count = Session::get('old_emails_count', $emails_count);
    $old_bugs_count = Session::get('old_bugs_count',$bugs_count);
    $old_sugs_count = Session::get('old_sugs_count',$sugs_count);

    Session::set('old_pictures_count', $pictures_count);
    Session::set('old_users_count', $users_count);
    Session::set('old_emails_count', $emails_count);
    Session::set('old_bugs_count', $bugs_count);
    Session::set('old_sugs_count', $sugs_count);

    $new_pictures = $pictures_count - $old_pictures_count;
    $new_users = $users_count - $old_users_count;
    $new_emails = $emails_count - $old_emails_count;
    $new_bugs = $bugs_count - $old_bugs_count;
    $new_sugs = $sugs_count - $old_sugs_count;


    View::share('pictures_count', $pictures_count);
    View::share('users_count', $users_count);
    View::share('emails_count', $emails_count);
    View::share('bugs_count', $bugs_count);
    View::share('sugs_count', $sugs_count);
    View::share('new_pictures', $new_pictures);
    View::share('new_users', $new_users);
    View::share('new_emails', $new_emails);
    View::share('new_bugs', $new_bugs);
    View::share('new_sugs', $new_sugs);
};



Route::when('admin/*', 'admin');
Route::when('admin', 'admin');

Route::group([ 'prefix' => 'admin', 'namespace' => 'backend' ], function () {

	Route::get('/', 'HomeController@index');
    Route::get('login', 'HomeController@isLogin');
    Route::post('login','HomeController@login');
    Route::get('logout','HomeController@logout');

    Route::post('picture/checkExists', array('as' => 'checkExists', 'uses' =>  'PictureController@checkExists'));
    Route::post('picture/upload', array('as' => 'upload', 'uses' =>  'PictureController@upload'));
    Route::get('picture/unnamed', array('as' => 'unnamed_pic', 'uses' =>  'PictureController@withoutNameAndKeywords'));
    Route::get('picture/named', array('as' => 'named_pic', 'uses' =>  'PictureController@withNameOrKeywords'));


	Route::resource('role', 'RoleController');
	Route::resource('user', 'UserController');
	Route::resource('email', 'EmailController');
	Route::resource('article', 'ArticleController');
	Route::resource('picture', 'PictureController');
	Route::resource('keyword', 'KeywordController');
	Route::resource('error', 'ErrorController');
	Route::resource('statistic', 'StatisticController');

});

Route::group(['namespace' => 'frontend' ], function () {
    //  auth filter
    Route::group(array('before' => 'auth'), function()
    {
        Route::get('profile', 'UserController@edit');
        Route::post('profile', 'UserController@update');
        Route::post('tempup', 'PictureController@uploadTemp');
        Route::get('upload', 'PictureController@create');
        Route::post('upload', 'PictureController@store');
        Route::get('likes', 'PictureController@likes');
        Route::post('img/comment/store', 'CommentController@store');
        Route::get('img/edit/{id}', 'PictureController@edit');
        Route::post('img/edit/{id}', 'PictureController@update');
    });
    //picture filter
    Route::group(array('before' => 'pic_permission'), function()
    {
        Route::delete('img/picture/destroy/{id}', 'PictureController@destroy');
    });

    //  comment filter
    Route::group(array('before' => 'comment_permission'), function()
    {
        Route::post('img/comment/update/{id}', 'CommentController@update');
        Route::delete('img/comment/destroy/{id}', 'CommentController@destroy');
    });


	Route::get('/', 'UserController@index');
	Route::get('sign-up', 'UserController@signUp');
	Route::post('sign-up', 'UserController@doSignUp');
	Route::post('password/reset', 'UserController@passwordResetLink');
	Route::get('password/reset/{token}', 'UserController@passwordReset');
	Route::post('password/reset/{token}', 'UserController@passwordChange');
	Route::get('logout', 'UserController@logout');
	Route::get('login', 'UserController@login');
	Route::post('login', 'UserController@doLogin');
	Route::get('explorer', 'PictureController@index');
	Route::get('ajax/keywords', 'PictureController@keywords');
	Route::get('img/search', 'PictureController@search');
    Route::get('img/show/{id}/{name?}', 'PictureController@show');
    Route::get('img/show/{id}/{name?}', 'PictureController@show');
    Route::get('img/show/{id}/{name?}', 'PictureController@show');
	Route::get('img/download/{name}', 'PictureController@download');
	Route::get('img/toggleLike/{id}', 'PictureController@toggleLike');
	Route::get('page/{name}', 'ArticleController@index');
	Route::get('contact', 'ArticleController@contact');
	Route::post('contact', 'ArticleController@send');
});
Route::get('fbauth/{auth?}',array('as'=>'facebookAuth','uses'=>'AuthController@getFacebookLogin'));
Route::get('gauth/{auth?}',array('as'=>'googleAuth','uses'=>'AuthController@getGoogleLogin'));
Route::get('register/verify/{confirmationCode}', ['as' => 'confirmation_path', 'uses' => 'RegistrationController@confirm']);
Route::post('queue/receive', function()
{
    return Queue::marshal();
});
// Route::get('ironmq',function ()
// {
//     $time = time();
//     Queue::push(function ($job) use($time)
//     {
//         File::append(app_path()."/time.txt",$time.PHP_EOL);
//     });
// });
/*Event::listen('illuminate.query', function($query)
{
    var_dump($query);
});*/

/*array (size=5)
  'city' => string 'imlil' (length=5)
  'country' => string 'Italy' (length=5)
  'url' => string 'http://localhost:8000/page/about' (length=32)
  'time' => int 1436548913
  'count' => int 1*/

app/controllers/backend/ArticleController.php
<?php
namespace backend;
use View; use Article; use Input; use Redirect; use Validator; use Session;
class ArticleController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$articles = Article::paginate(10);
		return View::make('backend.article.index', compact('articles'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		Session::flash('ckeditor_resources', '1');
		return View::make('backend.article.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{

		$name = Input::get('name');
		$content = Input::get('content');
		$validator = Validator::make(
		    array('name' => $name),
		    array('name' => 'required|min:2|unique:article')
		);
		if ($validator->fails())
		{
			$messages = $validator->messages();
		    return Redirect::to('admin/article/create')->withErrors($messages)->withInput();
		}
		// return $content;
		Article::create(array('name' => $name,
								'content' => $content));

		$messages = array('Un nouvel article vient de s\'inséré.');
		return Redirect::to('admin/article')->withMessages($messages);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$article = Article::find($id);
		return View::make('backend.article.show', compact('article'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		Session::flash('ckeditor_resources', '1');
		$article = Article::find($id);
		return View::make('backend.article.edit', compact('article'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$article = Article::find($id);
		$name = Input::get('name');
		$content = Input::get('content');
		$validator = Validator::make(
		    array('name' => $name),
		    array('name' => 'required|min:2|unique:article,id,'.$id)
		);
		if ($validator->fails())
		{
			$messages = $validator->messages();
		    return Redirect::to("admin/article/$id/edit")->withInput()->withErrors($messages);
		}

		$article->name = $name;
		$article->content = $content;
		$article->save();
		$messages = array('Le article a été bien modifié.');
		return Redirect::route('admin.article.index')->withMessages($messages);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$article = Article::find($id);
		if ($article->delete()) {
			$messages = array('L\'article a été bien supprimé.');
			return Redirect::route('admin.article.index')->withMessages($messages);
		}
	}


}

app/controllers/backend/EmailController.php
<?php
namespace backend;
use View; use Email; use Input; use Redirect; use Validator;
class EmailController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$mails = Email::paginate(10);
		// return $mails;
		return View::make('backend.email.index', compact('mails'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{

	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$email = Email::find($id);
		return View::make('backend.email.show', compact('email'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$email = Email::find($id);
		if ($email->delete()) {
			$messages = array('L\'email a été bien supprimé.');
			return Redirect::back()->withMessages($messages);
		}
	}


}

app/controllers/backend/ErrorController.php
<?php
namespace backend;
use View; use Error; use Input; use Redirect; use Validator;
class ErrorController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$app_errors = Error::paginate(10);
		return View::make('backend.error.index', compact('app_errors'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{

	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$error = Error::find($id);
		return View::make('backend.error.show', compact('error'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$error = Error::find($id);
		if ($error->delete()) {
			$messages = array('L\'error a été bien supprimé.');
			return Redirect::back()->withMessages($messages);
		}
	}


}

app/controllers/backend/HomeController.php
<?php namespace backend;
use Input; use View; use Auth; use Redirect; use User; use Hash; use Role; use Session; use Validator; use Picture;
class HomeController extends \BaseController {

	public function index()
	{
        // return dd(Auth::check());
		if (Auth::check() && Auth::user()->hasRole("admin")) {
            Session::flash('jscroll_resources', '1');
            $pictures = Picture::simplePaginate(12);
			return View::make('backend.user.index', compact('pictures'));
		} else {
			return Redirect::to('admin/login');
		}
	}


	public function isLogin()
	{
        // return dd(Auth::check());
        if (Auth::check() && Auth::user()->hasRole("admin")) {
            return Redirect::to('admin');
        }
		return View::make('backend.user.login');
	}


	public function login()
	{
		$rules = array(
            'login'    => 'required',
            'password' => 'required' 
        );

        $validator = Validator::make(Input::all(), $rules);

        if ($validator->fails())
        {
            $messages = $validator->messages();

            return Redirect::to("admin/login")->withInput(Input::except('password'))->withErrors($messages);
        }

        $userdata = array(
            'login' => Input::get('login'),
            'password' => Input::get('password'),
            'role_id' => Role::where('name','=','admin')->first()->id
        );
        if(Auth::attempt($userdata, Input::has("save_cnt"))) 
        {
            return Redirect::intended('admin');
        }
        else
        {
            $errors = array( "Vos identifiants sont incorrects ou vous n'avez pas le droit d'accès .");
            return Redirect::to('admin/login')->withErrors($errors);
        }
	}

    public function logout()
    {
        Auth::logout();
        Session::flush();
        return Redirect::to('admin/login');
    }

}

app/controllers/backend/KeywordController.php
<?php
namespace backend;
use View; use Keyword; use Input; use Redirect; use Validator; use Session;
class KeywordController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$keywords = Keyword::paginate(10);
		return View::make('backend.keyword.index', compact('keywords'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		Session::flash('ckeditor_resources', '1');
		return View::make('backend.keyword.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{

		$name = Input::get('name');
		$content = Input::get('content');
		$validator = Validator::make(
		    array('name' => $name),
		    array('name' => 'required|min:5|unique:keyword')
		);
		if ($validator->fails())
		{
			$messages = $validator->messages();
		    return Redirect::to('admin/keyword/create')->withErrors($messages)->withInput();
		}
		// return $content;
		Keyword::create(array('name' => $name,
								'content' => $content));

		$messages = array('Un nouvel keyword vient de s\'inséré.');
		return Redirect::to('admin/keyword')->withMessages($messages);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$keyword = Keyword::find($id);
		return View::make('backend.keyword.show', compact('keyword'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$keyword = Keyword::find($id);
		return View::make('backend.keyword.edit', compact('keyword'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$keyword = Keyword::find($id);

		$Keyword = Input::get('keyword');
		
		$validator = Validator::make(
		    array('Keyword' => $Keyword),
		    array('Keyword' => 'required|min:3|unique:keyword')
		);
		if ($validator->fails())
		{
			$messages = $validator->messages();
		    return Redirect::to("admin/keyword/$id/edit")->withInput()->withErrors($messages);
		}
		
		$keyword->Keyword = $Keyword;
		$keyword->save();
		$messages = array('Le mot clé a été bien modifié.');
		return Redirect::route('admin.keyword.index')->withMessages($messages);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$keyword = Keyword::find($id);
		if ($keyword->delete()) {
			$messages = array('Le mot clé a été bien supprimé.');
			return Redirect::route('admin.keyword.index')->withMessages($messages);
		}
	}


}

app/controllers/backend/StatisticController.php
<?php
namespace backend;
use View; use Article; use Input; use Redirect; use Validator; use Session; use Email; use Mail; use Statistic; use Request; use DateTime;
class StatisticController extends \BaseController {

	public function index()
	{
		$statistics = Statistic::paginate(10);
		return View::make('backend.statistic.index', compact('statistics'));
	}

	public function show($id)
	{
		$statistic = Statistic::find($id);
		return View::make('backend.statistic.show', compact('statistic'));
	}

	public function destroy($id)
	{
		$statistic = Statistic::find($id);
		if ($statistic->delete()) {
			$messages = array('La statistique a été bien supprimée.');
			return Redirect::back()->withMessages($messages);
		}
	}
}

app/views/backend/picture/create.blade.php
@extends('backend.layouts.main')
	@section('content')<!-- 
	 --><div class="content">
		 	<div class="title">
		 		<h1>Nouvelle(s) photo(s)</h1>
		 	</div>
		 	<div class="form ">
				<div class="error-msg msg">
		 			<p>Dés que les photos sont sélectionnées l'upload va commencer automatiquement !</p>
		 		</div>
		 		@if(Session::has('messages'))
					<div class="ok-msg msg">
			 			@foreach (Session::get('messages') as $msg)
						    <p>{{ $msg}}</p>
						@endforeach
			 		</div>
		 		@endif
		 		{{ Form::open() }}
		  			 {{Form::file('pictures', array('id' => 'pictures_upload', 'multiple' => 'true'))}}
		  			<div class="btn-panel">
		  				<!-- <a class="button-ok" href="javascript:$('#pictures_upload').uploadify('upload')" title="Ajouter"><i class="fa fa-check"></i>Ajouter</a> -->
		  				<a class="button" href="{{ url('admin/picture')}}" taype="button" title="Annuler"><i class="fa fa-arrow-left"></i>Annuler</a>
		  			</div>
		  			

				{{ Form::close() }}	
		 	</div>
		 	
		</div>	
	@stop

app/views/backend/picture/edit.blade.php
@extends('backend.layouts.main')
	@section('content')<!--
	 --><div class="content">
		 	<div class="title">
		 		<h1>Photo {{$picture->name}}</h1>
		 	</div>
		 	<div class="form ">
		 		@if($errors->all())
					<div class="error-msg msg">
			 			@foreach ($errors->all() as $error)
						    <p>{{ $error}}</p>
						@endforeach
			 		</div>
		 		@endif
		 		@if(Session::has('errors2'))
					<div class="error-msg msg">
			 			@foreach (Session::get('errors2') as $msg)
						    <p>{{ $msg}}</p>
						@endforeach
			 		</div>
		 		@endif
		 		@if(Session::has('messages'))
					<div class="ok-msg msg">
			 			@foreach (Session::get('messages') as $msg)
						    <p>{{ $msg}}</p>
						@endforeach
			 		</div>
		 		@endif
		 		{{ Form::model($picture,array('method' => 'PUT', 'files' => true, 'route' => ['admin.picture.update', $picture->id])) }}
		 			{{ HTML::image('content/'.$picture->url_origin, '', array('class' => 'img-picture-preview')) }}
	 				<div class="form_group">
		 				{{Form::label('new_picture', 'Nouvelle photo : ')}} {{Form::file('new_picture')}}
		 			</div>
		  			<div class="form_group">
						{{Form::label('validated', 'Validée : ')}} {{Form::select('validated', array('1' => 'Oui', '0' => 'Non'), $picture->validated )}}
		  			</div>
		  			<div class="form_group">
						{{Form::label('keywords', 'Les mots cles : ')}} {{Form::select('keywords',$all_keywords , $picture_keywords , array("multiple", 'name' => 'keywords[]'))}}
		  			</div>

		  			<div class="btn-panel">
		  				<button class="button-ok" type="submit" title="Valider"><i class="fa fa-check"></i>Modifer</button>
		  				<a class="button" href="{{ url('admin/picture')}}" type="button" title="Annuler"><i class="fa fa-arrow-left"></i>Annuler</a>
		  			</div>
				{{ Form::close() }}
		 	</div>

		</div>
		<script  type="text/javascript">
			$("#keywords").select2({
			    placeholder: "Ajoutez des mots cles.",
			    allowClear: true,
			     maximumSelectionSize: 5
			});
		</script>
	@stop

app/views/backend/picture/index.blade.php
@extends('backend.layouts.main')
	@section('content')<!-- 
	 --><div class="content">
	 	<a class="button-new" href="{{ url('admin/picture/create')}}" title="Nouvelle(s) photo(s)"><i class="fa fa-plus-circle"></i>Nouvelle(s) photo(s)</a>
	 	@if($errors->all())
			<div class="error-msg msg">
	 			@foreach ($errors->all() as $error)
				    <p>{{ $error}}</p>
				@endforeach
	 		</div>
 		@endif
 		@if(Session::has('errors'))
			<div class="error-msg msg">
	 			@foreach (Session::get('errors') as $msg)
				    <p>{{ $msg}}</p>
				@endforeach
	 		</div>
 		@endif
 		@if(Session::has('messages'))
			<div class="ok-msg msg">
	 			@foreach (Session::get('messages') as $msg)
				    <p>{{ $msg}}</p>
				@endforeach
	 		</div>
 		@endif
			<table class="grid">
						<thead>
							<tr>
								<th>Nom</th>
								<th>Poids</th>
								<th>Taille</th>
								<th>Aperçu</th>
								<th>Texte</th>
								<th>Validé</th>
								<th>Ajouté par</th>
								<th>Crée à</th>
								<th>Modifiée à</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>

							@foreach ($pictures as $picture)
							    <tr>
									<td> {{$picture->clipedName()}}</td>
									<td> {{$picture->sizeUnit()}}</td>
									<td> {{$picture->dimension}}</td>
									<td>
										<div class="picture-preview" style="background-image: url({{url('content/'.$picture->url_origin);}});">
										</div>
									</td>
									<td> 
									</td><!-- texte -->
									<td> {{$picture->validated}}</td>
									<td>{{$picture->user->login}} </td>
									<td> {{$picture->created_at}}</td>
									<td> {{$picture->updated_at}}</td>
									<td>
										<a class="button" href="{{ route('admin.picture.edit', $picture->id);}}"><i class="fa fa-pencil-square-o"></i></a>
										
										{{Form::open(array('method' => 'DELETE','class'=>'btn-form', 'route' => ['admin.picture.destroy', $picture->id]))}}
											<button class="button" type="submit"><i class="fa fa-times"></i></button>
										{{Form::close()}}
									</td>
								</tr>
							@endforeach
							
							</tr>

						</tbody>
					</table>		
					{{$pictures->links()}}	
		</div>	
	@stop